# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merge_type', models.CharField(choices=[('merge', 'merge'), ('deploy', 'deploy')], max_length=6)),
                ('merge_status', models.CharField(choices=[('raised', 'raised'), ('viewed', 'viewed'), ('started', 'started'), ('failed', 'failed'), ('resolved', 'resolved')], default='raised', max_length=8)),
                ('raised_on', models.DateTimeField()),
                ('resolved_on', models.DateTimeField()),
            ],
        ),
    ]
