# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merge',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='merge',
            name='raised_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
