# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0002_auto_20170718_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='merge',
            name='branch_name',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merge',
            name='repos',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
