# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0003_auto_20170719_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.RemoveField(
            model_name='merge',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='merge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='merger.Merge'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merge',
            name='environment',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merge',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='merger.Branch'),
            preserve_default=False,
        ),
    ]
