# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0004_auto_20170719_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merge',
            name='merge_type',
            field=models.CharField(choices=[('merge', 'merge'), ('deploy', 'deploy')], default='merge', max_length=6),
        ),
        migrations.AlterField(
            model_name='merge',
            name='resolved_on',
            field=models.DateTimeField(null=True),
        ),
    ]
