# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0005_auto_20170719_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merge',
            name='resolved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
